// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BASSFit
List BASSFit(const arma::mat X, const arma::mat xy, const arma::vec ns, const int C, const int R, const int k, const double alpha0, const arma::mat Psi0, const int n0, const int burnin, const int nsample, const String method, const int potts_burnin, const int potts_nsample, const double step_size, const double tol, const arma::uvec init_c, const arma::uvec init_z, const arma::mat init_mu, const double init_beta);
RcppExport SEXP _BASS_BASSFit(SEXP XSEXP, SEXP xySEXP, SEXP nsSEXP, SEXP CSEXP, SEXP RSEXP, SEXP kSEXP, SEXP alpha0SEXP, SEXP Psi0SEXP, SEXP n0SEXP, SEXP burninSEXP, SEXP nsampleSEXP, SEXP methodSEXP, SEXP potts_burninSEXP, SEXP potts_nsampleSEXP, SEXP step_sizeSEXP, SEXP tolSEXP, SEXP init_cSEXP, SEXP init_zSEXP, SEXP init_muSEXP, SEXP init_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type xy(xySEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< const int >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type R(RSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type Psi0(Psi0SEXP);
    Rcpp::traits::input_parameter< const int >::type n0(n0SEXP);
    Rcpp::traits::input_parameter< const int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< const int >::type nsample(nsampleSEXP);
    Rcpp::traits::input_parameter< const String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const int >::type potts_burnin(potts_burninSEXP);
    Rcpp::traits::input_parameter< const int >::type potts_nsample(potts_nsampleSEXP);
    Rcpp::traits::input_parameter< const double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type init_c(init_cSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type init_z(init_zSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type init_mu(init_muSEXP);
    Rcpp::traits::input_parameter< const double >::type init_beta(init_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(BASSFit(X, xy, ns, C, R, k, alpha0, Psi0, n0, burnin, nsample, method, potts_burnin, potts_nsample, step_size, tol, init_c, init_z, init_mu, init_beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BASS_BASSFit", (DL_FUNC) &_BASS_BASSFit, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_BASS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
