# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gibbs <- function(X, xy, Ns, C, R, initMethod, kappa, alpha0, a, b, k, warmUp, numSamples, betaEstApproach, betaIn, betaMax, epsilon, M, B, NHC) {
    .Call(`_BASS_Gibbs`, X, xy, Ns, C, R, initMethod, kappa, alpha0, a, b, k, warmUp, numSamples, betaEstApproach, betaIn, betaMax, epsilon, M, B, NHC)
}

avgNeighbors <- function(r, coord) {
    .Call(`_BASS_avgNeighbors`, r, coord)
}

testFastBetaEst <- function(x, coord, r, beta, epsilon, S, NHC) {
    .Call(`_BASS_testFastBetaEst`, x, coord, r, beta, epsilon, S, NHC)
}

testPottsSampling <- function(coord, r, beta, R, M) {
    .Call(`_BASS_testPottsSampling`, coord, r, beta, R, M)
}

testPostBeta <- function(x, coord, R, beta, epsilon, M, S) {
    .Call(`_BASS_testPostBeta`, x, coord, R, beta, epsilon, M, S)
}

