# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BASSFit <- function(X, xy, ns, C, R, k, alpha0, Psi0, n0, burnin, nsample, method, potts_burnin, potts_nsample, step_size, tol, init_c, init_z, init_mu, init_beta) {
    .Call(`_BASS_BASSFit`, X, xy, ns, C, R, k, alpha0, Psi0, n0, burnin, nsample, method, potts_burnin, potts_nsample, step_size, tol, init_c, init_z, init_mu, init_beta)
}

